# -*- coding: utf-8 -*-
"""in_out.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GHJTCpFisc46QLAXgoH1ONO8F1IrZ5yp
"""

import pandas as pd
import numpy as np
df=pd.read_csv("/content/data-ori.csv")

df

df['SEX']=df['SEX'].apply(lambda x: 1 if x == 'M' else 0)

df['SOURCE']=df['SOURCE'].apply(lambda x: 1 if x == 'in' else 0)

df

from sklearn.ensemble import RandomForestClassifier

X=df.iloc[:,:-1]

y=df.SOURCE

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

# creating a RF classifier
clf = RandomForestClassifier(n_estimators = 1000) 

# Training the model on the training dataset
# fit function is used to train the model using the training sets as parameters
clf.fit(X_train, y_train)
 
# performing predictions on the test dataset
y_pred = clf.predict(X_test)
 
# metrics are used to find accuracy or error
from sklearn import metrics 
print()
 
# using metrics module for accuracy calculation
print("ACCURACY OF THE MODEL: ", metrics.accuracy_score(y_test, y_pred))

